name: publish and run docker image
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - develop
      - master
jobs:
  push_to_registry:
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/develop') || \
      (github.event_name == 'push' && github.ref == 'refs/heads/master') || \
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master')
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ts-express-server:${{ github.sha }}
            ghcr.io/${{ github.repository }}/ts-express-server:${GITHUB_REF##*/}
            ghcr.io/${{ github.repository }}/ts-express-server:latest
  deploy_to_staging:
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/develop')
    name: Deploy to aws
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: deploy
      run: |
        sh deploying-to-staging-flow.sh