name: Manual Trigger

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          SECURITY_GROUP: ${{ secrets.SECURITY_GROUP_ID }}
        run: |
          # https://github.com/haythem/public-ip
          IP_ADDRESS=`echo ${{ steps.ip.outputs.ipv4 }}`

          # AWS CLIをインストール
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

          # AWS CLIに設定をする
          printf "${ACCESS_KEY}\n${SECRET_ACCESS_KEY}\nap-northeast-1\njson\n" | aws configure --profile eyemovic-dev
          aws configure get aws_access_key_id --profile eyemovic-dev

          # SSHポートを開放する
          aws --profile eyemovic-dev ec2 authorize-security-group-ingress --group-id ${SECURITY_GROUP} --protocol tcp --port 22 --cidr "$IP_ADDRESS"/32

          # SSH接続して、git pullする
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
          cd /home/ec2-user &&
          docker stop $(docker ps -q) &&
          docker container prune --force &&
          docker rmi $(docker images -q) &&
          docker pull ghcr.io/kajirikajiri/ts-express-server/ts-express-server:b01581b3766a3083461c99773f21359e92267a35 &&
          docker run -d -p 3000:3000 51429776b715
          '

          # SSHのポートを閉じる
          aws --profile eyemovic-dev ec2 revoke-security-group-ingress --group-id ${SECURITY_GROUP} --protocol tcp --port 22 --cidr "$IP_ADDRESS"/32
